server:
  port: 8080

logging:
  level:
    root: info
    com.parcel.ms.otp: debug

spring:
  application:
    name: ms-parcel-otp
  mvc:
    converters:
      preferred-json-mapper: gson
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        max-attempts: 2

redis:
  server:
    urls: redis://cache:6379

queue:
  name: MAIL_Q


otp:
  delay: 30
  totalAttempts: 3
  length: 6
  expirationTime: 180

