server:
  port: 8091

logging:
  level:
    root: info
    com.etaksify.ms: debug

spring:
  application:
    name: ms-srp-generator
  mvc:
    converters:
      preferred-json-mapper: gson
  pathmatch:
    matching-strategy: ant_path_matcher
management:
  endpoint:
    health:
      show-details: "ALWAYS"

