server:
  port: 8080

logging:
  level:
    root: info
    com.etaksify.ms: debug

spring:
  application:
    name: ms-parcel-auth
  mvc:
    converters:
      preferred-json-mapper: gson
    pathmatch:
      matching-strategy: ant_path_matcher

feign:
  client:
    config:
      default:
        connectTimeout: 30_000 #ms
        readTimeout: 30_000 #ms
        loggerLevel: FULL
      ms-parcel-users:
        url: user:8080
        errorDecoder: com.parcel.ms.auth.client.user.UserClientErrorDecoder
      ms-parcel-courier:
        url: courier:8080
        errorDecoder: com.parcel.ms.auth.client.courier.CourierClientErrorDecoder

redis:
  server:
    urls: redis://cache:6379

jwt:
  accessToken:
    expirationTime: 1200
  refreshToken:
    expirationTime: 3600
    expirationCount: 50